
name: fe
channels:
#  - postelrich
  - conda-forge
dependencies:
  - python>3.5
  - numpy
  - simpleitk>2.0
  - matplotlib
  - nibabel
  - requests
  - scipy
  - scikit-learn
  - pip
# conda env create -f environment.yml
# activate and ->conda env update --file local.yml --prune
#or
# conda env update --name me --file local.yml --prune


